# Generated by Django 5.0 on 2023-12-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_likes_like_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
